
CREATE TABLE public.contact_messages (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  email varchar NOT NULL,
  subject varchar NOT NULL,
  message text NOT NULL,
  send_method varchar NOT NULL DEFAULT 'system',
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can insert contact_messages" ON public.contact_messages FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Authenticated can read contact_messages" ON public.contact_messages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated can update contact_messages" ON public.contact_messages FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated can delete contact_messages" ON public.contact_messages FOR DELETE TO authenticated USING (true);
